const KEY='stockflow-v5',OLD='stockflow-v4';
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('fr-FR').format(Math.round(Number(n)||0))+' DA';
const id=()=>{try{return crypto.randomUUID()}catch(e){return 'id-'+Date.now()+'-'+Math.random().toString(36).slice(2)}};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||JSON.parse(localStorage.getItem(OLD)||'null')||JSON.parse(localStorage.getItem('stockflow-v3')||'null')||{customers:[],temu:[]};
db.customers=(db.customers||[]).map(c=>({...c,id:c.id||id(),items:(c.items||[]).map(i=>({...i,id:i.id||id(),cost:+i.cost||0,received:!!i.received}))}));
db.temu=(db.temu||[]).map(t=>({...t,id:t.id||id(),status:t.status||'draft',checkedIds:t.checkedIds||[],cost:+t.cost||0,customerIds:t.customerIds||[]}));
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));return true}catch(e){alert('Impossible de sauvegarder. Vérifie l’espace disponible sur ton navigateur.');return false}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function customerTotal(c){return(c.items||[]).reduce((s,i)=>s+(+i.price||0)*(+i.quantity||0),0)}
function customerCost(c){return(c.items||[]).reduce((s,i)=>s+(+i.cost||0)*(+i.quantity||0),0)}
function customerProfit(c){return customerTotal(c)-customerCost(c)}
function itemCount(c){return(c.items||[]).reduce((s,i)=>s+(+i.quantity||0),0)}
function allItems(){return db.customers.flatMap(c=>(c.items||[]).map(i=>({...i,customer:c,temu:db.temu.find(t=>(t.customerIds||[]).includes(c.id))})))}
function statusLabel(s){return{waiting:'À regrouper',grouped:'Dans TEMU',received:'Reçue'}[s]||s}
function temuStatusLabel(s){return{draft:'À préparer',ordered:'Commandée',shipped:'Expédiée',transit:'En transit',received:'Reçue'}[s]||'À préparer'}
function temuTotal(t){return(t.customerIds||[]).reduce((s,cid)=>{const c=db.customers.find(x=>x.id===cid);return s+(c?customerTotal(c):0)},0)}
function temuCost(t){return +t.cost||0}
function temuProfit(t){return temuTotal(t)-temuCost(t)}
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));const el=$('#'+v);if(el)el.classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if($('#title'))$('#title').textContent={home:'Bonjour 👋',customers:'Commandes clientes',temu:'Mes commandes TEMU',receive:'Réception des colis'}[v]||'StockFlow'}
function ensureExtras(){if(!$('#advancedStats')&&$('.stats'))$('.stats').insertAdjacentHTML('afterend','<div id="advancedStats" class="advanced-stats"><div><span>💰 CA vendu</span><b id="dashRevenue">0 DA</b><small>commandes actives</small></div><div><span>💸 Coût achat</span><b id="dashCost">0 DA</b><small>commandes TEMU</small></div><div><span>📈 Bénéfice</span><b id="dashProfit">0 DA</b><small>estimé</small></div><div><span>🚚 En route</span><b id="dashTransit">0</b><small>commandes TEMU</small></div></div>')}
function renderCustomers(){const q=($('#customerSearch')?.value||'').toLowerCase(),st=$('#customerStatus')?.value||'all';const list=db.customers.filter(c=>(c.status==='waiting'||c.status==='received')&&(st==='all'||c.status===st)&&(`${c.client} ${c.phone} ${c.number} ${(c.items||[]).map(i=>i.product).join(' ')}`.toLowerCase().includes(q)));$('#customerList').innerHTML=list.map(c=>`<article class="customer-card clickable" onclick="openCustomerDetails('${c.id}')">${c.photo?`<img class="order-photo" src="${c.photo}" alt="Photo">`:''}<div class="customer-top"><div><span class="order-no">#${esc(c.number)}</span><h3>${esc(c.client)}</h3><p>${esc(c.phone||'')} · ${esc(c.date||'')}</p></div><span class="badge ${c.status}">${statusLabel(c.status)}</span></div><div class="items">${(c.items||[]).map(i=>`<div><span>${esc(i.product)} <b>×${i.quantity}</b></span><strong>${money(i.price*i.quantity)}</strong></div>`).join('')}</div><div class="customer-bottom"><b>Total ${money(customerTotal(c))}</b><span class="view-details">Voir la fiche →</span></div></article>`).join('')||'<div class="empty">Aucune commande à afficher.</div>'}
function renderTemu(){if(!$('#temuList'))return;if(!db.temu.length){$('#temuList').innerHTML='<div class="empty big-empty">Aucune commande TEMU pour le moment.<br><button class="add" onclick="openTemu()">Créer ma première commande</button></div>';return}$('#temuList').innerHTML=db.temu.slice().reverse().map(t=>{const clients=(t.customerIds||[]).map(cid=>db.customers.find(c=>c.id===cid)).filter(Boolean);return `<article class="temu-card temu-clickable" onclick="openTemuDetails('${t.id}')"><div class="temu-head"><div><span class="order-no">${esc(t.ref)}</span><h3>🛍️ Commande TEMU</h3><p>${esc(t.date)} · ${clients.length} cliente${clients.length>1?'s':''} · ${clients.reduce((s,c)=>s+itemCount(c),0)} articles</p></div><span class="badge">${temuStatusLabel(t.status)}</span></div><div class="temu-summary">${clients.slice(0,3).map(c=>`<div class="temu-client-chip"><span><b>${esc(c.client)}</b><small>#${c.number} · ${itemCount(c)} article${itemCount(c)>1?'s':''}</small></span><strong>${money(customerTotal(c))}</strong></div>`).join('')}${clients.length>3?`<div class="more-clients">+ ${clients.length-3} autres clientes</div>`:''}</div><div class="temu-foot"><b>${money(temuTotal(t))}</b><span class="view-details">Ouvrir →</span></div></article>`}).join('')}
function renderReceive(){if(!$('#receiveResults'))return;const q=($('#receiveSearch')?.value||'').toLowerCase().trim();if(!q){$('#receiveResults').innerHTML='<div class="receive-tip">🔎 Recherche un produit, une cliente, un téléphone ou une référence TEMU.</div>';return}const list=allItems().filter(x=>!x.received&&`${x.product} ${x.customer.client} ${x.customer.phone} ${x.customer.number} ${x.temu?.ref||''}`.toLowerCase().includes(q));$('#receiveResults').innerHTML=list.map(x=>`<div class="receive-card"><div><strong>${esc(x.product)}</strong><small>${esc(x.customer.client)} · ${esc(x.customer.phone||'')}</small></div><button class="add" onclick="receiveItem('${x.customer.id}','${x.id}')">✓ Reçu</button></div>`).join('')||'<div class="empty">Aucun article trouvé.</div>'}
function render(){ensureExtras();const active=db.customers.filter(c=>c.status!=='received'),rev=active.reduce((s,c)=>s+customerTotal(c),0),cost=db.temu.reduce((s,t)=>s+temuCost(t),0),waiting=db.customers.filter(c=>c.status==='waiting'),trans=db.temu.filter(t=>['ordered','shipped','transit'].includes(t.status)).length;if($('#statPending'))$('#statPending').textContent=waiting.length;if($('#statTemu'))$('#statTemu').textContent=db.temu.length;if($('#statItems'))$('#statItems').textContent=allItems().filter(x=>!x.received).reduce((s,x)=>s+x.quantity,0);if($('#statRevenue'))$('#statRevenue').textContent=money(rev);if($('#dashRevenue'))$('#dashRevenue').textContent=money(rev);if($('#dashCost'))$('#dashCost').textContent=money(cost);if($('#dashProfit'))$('#dashProfit').textContent=money(rev-cost);if($('#dashTransit'))$('#dashTransit').textContent=trans;if($('#homeCustomers'))$('#homeCustomers').innerHTML=waiting.slice(0,5).map(c=>`<div class="mini-order clickable" onclick="openCustomerDetails('${c.id}')"><div><strong>#${c.number} · ${esc(c.client)}</strong><small>${itemCount(c)} article${itemCount(c)>1?'s':''}</small></div><b>${money(customerTotal(c))}</b></div>`).join('')||'<div class="empty">Tout est regroupé ✨</div>';renderCustomers();renderTemu();renderReceive()}
function addItem(d={}){const r=document.createElement('div');r.className='form-item';r.innerHTML=`<input class="ip" placeholder="Coque iPhone 16 / accessoire auto" value="${esc(d.product||'')}" required><input class="iq" type="number" min="1" value="${d.quantity||1}" required><input class="iprice" type="number" min="0" placeholder="Prix de vente DA" value="${d.price||''}" required><input class="icost" type="number" min="0" value="${d.cost||''}" hidden><button type="button">×</button>`;r.querySelector('button').onclick=()=>r.remove();$('#items').appendChild(r)}
function openCustomer(){const f=$('#customerForm');f.reset();f.date.value=new Date().toISOString().slice(0,10);$('#items').innerHTML='';$('#photoPreview').innerHTML='';window.photoData='';addItem();$('#modal').classList.remove('hidden')}
function openCustomerDetails(cid){const c=db.customers.find(x=>x.id===cid);if(!c)return;let m=$('#customerDetailModal');if(!m){m=document.createElement('div');m.id='customerDetailModal';m.className='modal hidden';document.body.appendChild(m)}m.innerHTML=`<div class="modal-box customer-detail-box"><div class="modal-title"><div><p class="eyebrow">FICHE CLIENTE</p><h2>👤 ${esc(c.client)}</h2><p>#${esc(c.number)} · ${esc(c.phone||'Téléphone non renseigné')}</p></div><button onclick="this.closest('.modal').classList.add('hidden')">×</button></div>${c.photo?`<img class="detail-photo" src="${c.photo}">`:''}<div class="detail-items">${(c.items||[]).map(i=>`<div><span>${esc(i.product)} <b>×${i.quantity}</b></span><strong>${money(i.price*i.quantity)}</strong></div>`).join('')}</div>${c.note?`<div class="detail-note">📝 ${esc(c.note)}</div>`:''}<div class="actions"><button class="cancel" onclick="this.closest('.modal').classList.add('hidden')">Fermer</button></div></div>`;m.classList.remove('hidden')}
function closeTemuDetails(){$('#temuDetailModal')?.classList.add('hidden')}
function openTemuDetails(tid){const t=db.temu.find(x=>x.id===tid);if(!t)return;let m=$('#temuDetailModal');if(!m){m=document.createElement('div');m.id='temuDetailModal';m.className='modal hidden';document.body.appendChild(m)}const clients=(t.customerIds||[]).map(cid=>db.customers.find(c=>c.id===cid)).filter(Boolean);m.innerHTML=`<div class="modal-box temu-detail-box"><div class="modal-title"><div><p class="eyebrow">COMMANDE TEMU</p><h2>🛍️ ${esc(t.ref)}</h2><p>${esc(t.date)} · ${clients.length} clientes</p></div><button onclick="closeTemuDetails()">×</button></div><div class="temu-status-panel"><div><strong>Suivi de la commande</strong><small>${temuStatusLabel(t.status)}</small></div><select onchange="changeTemuStatus('${t.id}',this.value)"><option value="draft" ${t.status==='draft'?'selected':''}>À préparer</option><option value="ordered" ${t.status==='ordered'?'selected':''}>Commandée</option><option value="shipped" ${t.status==='shipped'?'selected':''}>Expédiée</option><option value="transit" ${t.status==='transit'?'selected':''}>En transit</option><option value="received" ${t.status==='received'?'selected':''}>Reçue</option></select></div><div class="temu-detail-summary"><div><span>Clientes</span><b>${clients.length}</b></div><div><span>Articles</span><b>${clients.reduce((s,c)=>s+itemCount(c),0)}</b></div><div><span>Total clientes</span><b>${money(temuTotal(t))}</b></div><div><span>Coût TEMU</span><b>${t.cost?money(t.cost):'Non renseigné'}</b></div></div><div class="detail-section-title"><div><h3>Commandes clientes</h3><small>Toutes les commandes clientes regroupées dans cette commande TEMU.</small></div></div><div class="detail-client-list">${clients.map(c=>`<article class="detail-client-card">${c.photo?`<img class="detail-photo" src="${c.photo}">`:''}<div class="detail-client-head"><div><span class="order-no">#${esc(c.number)}</span><h3>${esc(c.client)}</h3><p>📞 ${esc(c.phone||'Téléphone non renseigné')} · ${esc(c.date)}</p></div><strong>${money(customerTotal(c))}</strong></div><div class="detail-items">${(c.items||[]).map(i=>`<div><span>${esc(i.product)} <b>×${i.quantity}</b></span><strong>${money(i.price*i.quantity)}</strong></div>`).join('')}</div>${c.note?`<div class="detail-note">📝 ${esc(c.note)}</div>`:''}</article>`).join('')||'<div class="empty">Aucune commande cliente.</div>'}</div><div class="actions"><button class="cancel" onclick="closeTemuDetails()">Fermer</button></div></div>`;m.classList.remove('hidden')}
function setTemuCost(tid){const t=db.temu.find(x=>x.id===tid);if(!t)return;const v=prompt('Coût total TEMU en DA',t.cost||'');if(v===null)return;const n=parseFloat(v.replace(',','.'));if(!Number.isFinite(n)||n<0)return alert('Montant invalide.');t.cost=Math.round(n);save();render();openTemuDetails(tid)}
function changeTemuStatus(tid,status){const t=db.temu.find(x=>x.id===tid);if(!t)return;t.status=status;save();render();openTemuDetails(tid)}
function receiveItem(cid,iid){const c=db.customers.find(x=>x.id===cid),i=c?.items.find(x=>x.id===iid);if(!i)return;i.received=true;if(c.items.every(x=>x.received)){c.status='received';const t=db.temu.find(x=>(x.customerIds||[]).includes(c.id));if(t&&t.customerIds.every(x=>db.customers.find(y=>y.id===x)?.status==='received'))t.status='received'}save();render()}
function openTemu(){const waiting=db.customers.filter(c=>c.status==='waiting');if(!waiting.length){alert('Ajoute d’abord des commandes clientes à regrouper.');show('customers');return}const f=$('#temuForm');f.reset();f.date.value=new Date().toISOString().slice(0,10);$('#groupCandidates').innerHTML=waiting.map(c=>`<label class="candidate"><input type="checkbox" name="customer" value="${c.id}"><span><b>${esc(c.client)}</b><small>#${c.number} · ${(c.items||[]).map(i=>esc(i.product)).join(' · ')}</small></span><strong>${money(customerTotal(c))}</strong></label>`).join('');document.querySelectorAll('[name=customer]').forEach(x=>x.onchange=calcTemu);$('#temuModal').classList.remove('hidden');calcTemu()}
function calcTemu(){let n=0;document.querySelectorAll('[name=customer]:checked').forEach(x=>{const c=db.customers.find(c=>c.id===x.value);if(c)n+=customerTotal(c)});if($('#temuTotal'))$('#temuTotal').textContent=money(n)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));if($('#newCustomer'))$('#newCustomer').onclick=openCustomer;if($('#newCustomer2'))$('#newCustomer2').onclick=openCustomer;if($('#newTemu'))$('#newTemu').onclick=openTemu;if($('#newTemu2'))$('#newTemu2').onclick=openTemu;if($('#closeModal'))$('#closeModal').onclick=$('#cancelModal').onclick=()=>$('#modal').classList.add('hidden');if($('#closeTemu'))$('#closeTemu').onclick=$('#cancelTemu').onclick=()=>$('#temuModal').classList.add('hidden');if($('#addItem'))$('#addItem').onclick=()=>addItem();if($('#customerSearch'))$('#customerSearch').oninput=renderCustomers;if($('#customerStatus'))$('#customerStatus').onchange=renderCustomers;if($('#receiveSearch'))$('#receiveSearch').oninput=renderReceive;let photoData='';if($('#orderPhoto'))$('#orderPhoto').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{photoData=r.result;window.photoData=photoData;$('#photoPreview').innerHTML=`<div class="photo-preview"><img src="${r.result}"><button type="button" onclick="clearPhoto()">×</button></div>`};r.readAsDataURL(file)};window.clearPhoto=()=>{photoData='';window.photoData='';$('#orderPhoto').value='';$('#photoPreview').innerHTML=''};
$('#customerForm').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target),rows=[...document.querySelectorAll('#items .form-item')];if(!rows.length)return alert('Ajoute au moins un article.');const items=rows.map(r=>{const product=r.querySelector('.ip').value.trim(),quantity=Number(r.querySelector('.iq').value),price=Number(r.querySelector('.iprice').value);if(!product||!Number.isFinite(quantity)||quantity<1||!Number.isFinite(price)||price<0)throw new Error('Vérifie les articles et les prix.');return{id:id(),product,quantity,price,cost:0,received:false}});const customer={id:id(),number:String(Date.now()).slice(-6),client:String(f.get('client')||'').trim(),phone:String(f.get('phone')||'').trim(),date:f.get('date'),status:f.get('status')||'waiting',note:String(f.get('note')||'').trim(),photo:window.photoData||'',items};if(!customer.client||!customer.date)throw new Error('Remplis le nom et la date.');db.customers.push(customer);if(!save())return;e.target.reset();$('#modal').classList.add('hidden');$('#items').innerHTML='';render();show('customers')}catch(err){alert(err.message||'Impossible d’enregistrer la commande.')}};
$('#temuForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),ids=f.getAll('customer');if(!ids.length)return alert('Sélectionne au moins une commande cliente.');const t={id:id(),ref:f.get('ref')||'TM-'+String(f.get('date')).replaceAll('-','').slice(2),date:f.get('date'),customerIds:ids,status:'draft',checkedIds:[],cost:0};db.temu.push(t);ids.forEach(cid=>{const c=db.customers.find(x=>x.id===cid);if(c){c.status='grouped';c.temuId=t.id}});save();$('#temuModal').classList.add('hidden');render();show('temu')};
if($('#exportBtn'))$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='stockflow-backup.json';a.click()};}
bind();render();